### ISSUE TITLE
Monterrey 12.3.1 don't work.

### ISSUE THREAD

**Issue by paulomcnally** [paulomcnally/opencore-monterey#1]
Hi @sileshn

Any recommendation to fix? I see https://github.com/sileshn/Ryzentosh/issues/5 but have too changes on the last months.

**Comment by sileshn** [comment]
which version of Monterey are you on? If version is less than 12.3, then you need [this](https://github.com/sileshn/Ryzentosh/commit/b5c627ce5f7fdc2a08b056a308b617e038715311) & [this](https://github.com/sileshn/Ryzentosh/commit/9b6957f7958667c726282c6bdaa1ad6de59770b2) to fix booting on versions 12.3 and above.

**Comment by paulomcnally** [comment]
Let me check. 😁

**Comment by paulomcnally** [comment]
Solved with youre feedback. Thanks again @sileshn
